export enum MODULE_CONTROL{
    MODULE01="THÔNG TIN THỊ TRƯỜNG VÀ TÌM KIẾM ĐỐI TÁC KINH DOANH",
    MODULE02="QUẢN LÝ THÔNG TIN THỊ TRƯỜNG VÀ TÌM KIẾM ĐỐI TÁC KINH DOANH",
    MODULE03="QUẢN LÝ DỮ LIỆU CHUYÊN NGÀNH",
    MODULE04="QUẢN LÝ BÁO CÁO CHUYÊN NGÀNH"
}