export const data_xk_t11 = [
    { ten_hang_hoa: 'Quốc tế Hoa Lư', id_cua_khau: 1, san_luong_tht: 0, tri_gia_tht: 18864530, uth_cung_ky: -2.9, uth_so_thang_trc: 59.8, san_luong_cong_don: 0, tri_gia_cong_don: 166257861, uth_cung_ky_cong_don: -8.3, uth_so_khn: 0 },
    { ten_hang_hoa: 'Hàng hoá Nhập khẩu', id_cua_khau: 1, san_luong_tht: 0, tri_gia_tht: 18864530, uth_cung_ky: 0, uth_so_thang_trc: 0, san_luong_cong_don: 0, tri_gia_cong_don: 165315011, uth_cung_ky_cong_don: 0, uth_so_khn: 0 },
    { ten_hang_hoa: 'Mua bán trao đổi cư dân biên giới', id_cua_khau: 1, san_luong_tht: 0, tri_gia_tht: 0, uth_cung_ky: 0, uth_so_thang_trc: 0, san_luong_cong_don: 0, tri_gia_cong_don: 0, uth_cung_ky_cong_don: 0, uth_so_khn: 0 },
    { ten_hang_hoa: 'Hàng hoá kinh doanh tạm nhập', id_cua_khau: 1, san_luong_tht: 0, tri_gia_tht: 0, uth_cung_ky: 0, uth_so_thang_trc: 0, san_luong_cong_don: 0, tri_gia_cong_don: 942850, uth_cung_ky_cong_don: -23.9, uth_so_khn: 0 },
    { ten_hang_hoa: 'Loại hình kinh doanh khác', id_cua_khau: 1, san_luong_tht: 0, tri_gia_tht: 0, uth_cung_ky: 0, uth_so_thang_trc: 0, san_luong_cong_don: 0, tri_gia_cong_don: 0, uth_cung_ky_cong_don: 0, uth_so_khn: 0 },
    { ten_hang_hoa: 'Chính Hoàng Diệu', id_cua_khau: 2, san_luong_tht: 0, tri_gia_tht: 10436680, uth_cung_ky: 419, uth_so_thang_trc: 502.4, san_luong_cong_don: 0, tri_gia_cong_don: 38301595, uth_cung_ky_cong_don: 222, uth_so_khn: 0 },
    { ten_hang_hoa: 'Hàng hoá Nhập khẩu', id_cua_khau: 2, san_luong_tht: 0, tri_gia_tht: 10436680, uth_cung_ky: 0, uth_so_thang_trc: 0, san_luong_cong_don: 0, tri_gia_cong_don: 38301595, uth_cung_ky_cong_don:0, uth_so_khn: 0 },
    { ten_hang_hoa: 'Mua bán trao đổi cư dân biên giới', id_cua_khau: 2, san_luong_tht: 0, tri_gia_tht: 0, uth_cung_ky: 0, uth_so_thang_trc: 0, san_luong_cong_don: 0, tri_gia_cong_don: 0, uth_cung_ky_cong_don: 0, uth_so_khn: 0 },
    { ten_hang_hoa: 'Hàng hoá kinh doanh tạm nhập', id_cua_khau: 2, san_luong_tht: 0, tri_gia_tht: 0, uth_cung_ky: 0, uth_so_thang_trc: 0, san_luong_cong_don: 0, tri_gia_cong_don: 0, uth_cung_ky_cong_don: 0, uth_so_khn: 0 },
    { ten_hang_hoa: 'Loại hình kinh doanh khác', id_cua_khau: 2, san_luong_tht: 0, tri_gia_tht: 0, uth_cung_ky: 0, uth_so_thang_trc: 0, san_luong_cong_don: 0, tri_gia_cong_don: 0, uth_cung_ky_cong_don: 0, uth_so_khn: 0 },
    { ten_hang_hoa: 'Chính Lộc Thịnh', id_cua_khau: 3, san_luong_tht: 0, tri_gia_tht: 12006800, uth_cung_ky: 90.6, uth_so_thang_trc: 242, san_luong_cong_don: 0, tri_gia_cong_don: 70251250, uth_cung_ky_cong_don: 88.2, uth_so_khn: 0 },
    { ten_hang_hoa: 'Hàng hoá Nhập khẩu', id_cua_khau: 3, san_luong_tht: 0, tri_gia_tht: 12006800, uth_cung_ky: 0, uth_so_thang_trc: 0, san_luong_cong_don: 0, tri_gia_cong_don: 70251250, uth_cung_ky_cong_don: 0, uth_so_khn: 0 },
    { ten_hang_hoa: 'Mua bán trao đổi cư dân biên giới', id_cua_khau: 3, san_luong_tht: 0, tri_gia_tht: 0, uth_cung_ky: 0, uth_so_thang_trc: 0, san_luong_cong_don: 0, tri_gia_cong_don: 0, uth_cung_ky_cong_don: 0, uth_so_khn: 0 },
    { ten_hang_hoa: 'Hàng hoá kinh doanh tạm nhập', id_cua_khau: 3, san_luong_tht: 0, tri_gia_tht: 0, uth_cung_ky: 0, uth_so_thang_trc: 0, san_luong_cong_don: 0, tri_gia_cong_don: 0, uth_cung_ky_cong_don: 0, uth_so_khn: 0 },
    { ten_hang_hoa: 'Loại hình kinh doanh khác', id_cua_khau: 3, san_luong_tht: 0, tri_gia_tht: 0, uth_cung_ky: 0, uth_so_thang_trc: 0, san_luong_cong_don: 0, tri_gia_cong_don: 0, uth_cung_ky_cong_don: 0, uth_so_khn: 0 },
    { ten_hang_hoa: 'Tổng', id_cua_khau: 3, san_luong_tht: 0, tri_gia_tht: 41308010, uth_cung_ky: 0, uth_so_thang_trc: 0, san_luong_cong_don: 0, tri_gia_cong_don: 274810706, uth_cung_ky_cong_don: 0, uth_so_khn: 0 }

]