export const Company_mock = {
    id: 1,
    ten_doanh_nghiep: '',

    id_nganh_nghe: '',
    ten_nganh_nghe: '',
    dia_chi: '',
    dia_chi_day_du: '',

    id_phuong_xa: 1,
    id_quan_huyen: 1,
    ten_quan_huyen: '',
    nganh_nghe_kd: '',
    nguoi_dai_dien: '',
    dien_thoai: '',
    mst: '',
    so_giay_cndkkd: '',
    ngay_cap_gcndkkd: '',

    id_loai_hinh: 1,
    loai_hinh_doanh_nghiep: '',
    von_kinh_doanh: 1,
    ngay_bat_dau_kd: '',
    email: '',
    so_lao_dong: 1,
    cong_suat_thiet_ke: 1,
    san_luong: 1,
    tieu_chuan_san_pham: '',

    id_danh_sach_co_so_truc_thuoc: 1,
    doanh_thu: 1,
    quy_mo_tai_san: 1,
    loi_nhuan: 1,
    nhu_cau_ban: '',
    nhu_cau_mua: '',
    nhu_cau_hop_tac: '',
    email_sct: '',
    so_lao_dong_sct: 1,
    cong_suat_thiet_ke_sct: 1,
    san_luong_sct: 1,
  }
  