export const data_xk_t11 = [
    { ten_hang_hoa: 'Quốc tế Hoa Lư', id_cua_khau: 1, san_luong_tht: 0, tri_gia_tht: 21704600, uth_cung_ky: 52.1, uth_so_thang_trc: 78.7, san_luong_cong_don: 0, tri_gia_cong_don: 100231409, uth_cung_ky_cong_don: 123.8, uth_so_khn: 0 },
    { ten_hang_hoa: 'Hàng hoá Xuất khẩu ', id_cua_khau: 1, san_luong_tht: 0, tri_gia_tht: 21704600, uth_cung_ky: 0, uth_so_thang_trc: 0, san_luong_cong_don: 0, tri_gia_cong_don: 100231409, uth_cung_ky_cong_don:0, uth_so_khn:0},
    { ten_hang_hoa: 'Mua bán trao đổi cư dân biên giới ', id_cua_khau: 1, san_luong_tht: 0, tri_gia_tht: 0, uth_cung_ky: 0, uth_so_thang_trc: 0, san_luong_cong_don: 0, tri_gia_cong_don: 0, uth_cung_ky_cong_don: 0, uth_so_khn: 0 },
    { ten_hang_hoa: 'Hàng hoá kinh doanh tạm xuất ', id_cua_khau: 1, san_luong_tht: 0, tri_gia_tht: 0, uth_cung_ky: 0, uth_so_thang_trc: 0, san_luong_cong_don: 0, tri_gia_cong_don: 0, uth_cung_ky_cong_don: 0, uth_so_khn: 0 },
    { ten_hang_hoa: 'Loại hình kinh doanh khác', id_cua_khau: 1, san_luong_tht: 0, tri_gia_tht: 0, uth_cung_ky: 0, uth_so_thang_trc: 0, san_luong_cong_don: 0, tri_gia_cong_don: 0, uth_cung_ky_cong_don: 0, uth_so_khn: 0 },
    { ten_hang_hoa: 'Chính Hoàng Diệu ', id_cua_khau: 2, san_luong_tht: 0, tri_gia_tht: 3856030, uth_cung_ky: 326.5, uth_so_thang_trc: 59, san_luong_cong_don:0, tri_gia_cong_don: 21759724, uth_cung_ky_cong_don: 205.5, uth_so_khn: 0 },
    { ten_hang_hoa: 'Hàng hoá Xuất khẩu ', id_cua_khau: 2, san_luong_tht: 0, tri_gia_tht: 3856030, uth_cung_ky: 0, uth_so_thang_trc: 0, san_luong_cong_don: 0, tri_gia_cong_don: 21759724, uth_cung_ky_cong_don: 0, uth_so_khn:0},
    { ten_hang_hoa: 'Mua bán trao đổi cư dân biên giới ', id_cua_khau: 2, san_luong_tht: 0, tri_gia_tht: 0, uth_cung_ky: 0, uth_so_thang_trc: 0, san_luong_cong_don: 0, tri_gia_cong_don: 0, uth_cung_ky_cong_don: 0, uth_so_khn: 0 },
    { ten_hang_hoa: 'Hàng hoá kinh doanh tạm xuất ', id_cua_khau: 2, san_luong_tht: 0, tri_gia_tht: 0, uth_cung_ky: 0, uth_so_thang_trc: 0, san_luong_cong_don: 0, tri_gia_cong_don: 0, uth_cung_ky_cong_don: 0, uth_so_khn: 0 },
    { ten_hang_hoa: 'Loại hình kinh doanh khác', id_cua_khau: 2, san_luong_tht: 0, tri_gia_tht: 0, uth_cung_ky: 0, uth_so_thang_trc: 0, san_luong_cong_don: 0, tri_gia_cong_don: 0, uth_cung_ky_cong_don: 0, uth_so_khn: 0 },
    { ten_hang_hoa: 'Chính Lộc Thịnh ', id_cua_khau: 3, san_luong_tht: 0, tri_gia_tht: 69270, uth_cung_ky: -85, uth_so_thang_trc: -80, san_luong_cong_don:0, tri_gia_cong_don: 6277109, uth_cung_ky_cong_don: 557.8, uth_so_khn: 0 },
    { ten_hang_hoa: 'Hàng hoá Xuất khẩu ', id_cua_khau: 3, san_luong_tht: 0, tri_gia_tht: 0, uth_cung_ky: 0, uth_so_thang_trc: 0, san_luong_cong_don: 0, tri_gia_cong_don: 6277109, uth_cung_ky_cong_don: 0, uth_so_khn: 0 },
    { ten_hang_hoa: 'Mua bán trao đổi cư dân biên giới ', id_cua_khau: 3, san_luong_tht: 0, tri_gia_tht: 0, uth_cung_ky: 0, uth_so_thang_trc: 0, san_luong_cong_don: 0, tri_gia_cong_don: 0, uth_cung_ky_cong_don: 0, uth_so_khn: 0 },
    { ten_hang_hoa: 'Hàng hoá kinh doanh tạm xuất ', id_cua_khau: 3, san_luong_tht: 0, tri_gia_tht: 0, uth_cung_ky: 0, uth_so_thang_trc: 0, san_luong_cong_don: 0, tri_gia_cong_don: 0, uth_cung_ky_cong_don: 0, uth_so_khn: 0 },
    { ten_hang_hoa: 'Loại hình kinh doanh khác', id_cua_khau: 3, san_luong_tht: 0, tri_gia_tht: 0, uth_cung_ky: 0, uth_so_thang_trc: 0, san_luong_cong_don: 0, tri_gia_cong_don: 0, uth_cung_ky_cong_don: 0, uth_so_khn: 0 },
    { ten_hang_hoa: 'Tổng ', id_cua_khau: 3, san_luong_tht: 0, tri_gia_tht: 25629900, uth_cung_ky: 0, uth_so_thang_trc: 0, san_luong_cong_don: 0, tri_gia_cong_don: 128268242, uth_cung_ky_cong_don: 0, uth_so_khn: 0 }
]